### ISSUE TITLE
Stable diffusion exiting when trying to generate

### ISSUE THREAD

**Issue by niikocap** [Haoming02/sd-webui-old-photo-restoration#20]
as i mention, it exits when i  try to generate on the terminal it stops after processing any idea how can i fix this

**Comment by Haoming02** [comment]
How about the console logs

**Comment by niikocap** [comment]
![image](https://github.com/Haoming02/sd-webui-old-photo-restoration/assets/51402422/9ab5dcbd-5bfc-4927-8726-faf9dc6a93ea)

here is the image 
also even when no options is selected its still exits

**Comment by niikocap** [comment]
should i run install.py first?

**Comment by Haoming02** [comment]
What GPU are you using?

**Comment by niikocap** [comment]
im using nvidia 950m  i use --lowvram

**Comment by Haoming02** [comment]
I sometimes get the same error about threading just generating images normally. Since it stems from the Webui, I can't really fix it on my end.

If it keeps happening though, you can try edit this line, https://github.com/Haoming02/sd-webui-old-photo-restoration/blob/main/scripts/main_function.py#L25, to:

```py
GPU_ID = -1
```
